### ISSUE TITLE
"Instructions" grid does not display in Edge browser

### ISSUE THREAD

**Issue by Raceous** [viresh-ratnakar/exolve#28] opened 2020-05-25 01:12 UTC
The latest 1Across grid, "Instructions", does not display in Microsoft Edge or Internet Explorer on Windows 10.
Here is a screenshot from Edge. (Enlarging the Edge window does not help.) The appearance in IE is similar.
![image](https://user-images.githubusercontent.com/54013910/82769560-f74a3d80-9de9-11ea-8b11-f52a0685dabd.png)

**Comment by viresh-ratnakar** [comment] 2020-05-25 01:25
Hmm, I have zero access right now to a Windows machine, unfortunately.

If you can bring up the JavaScript console and see if there are any error
messages, that might help.

**Comment by viresh-ratnakar** [comment] 2020-05-25 01:27
Another useful piece of info would be whether some older grid works (to
identify if the issue is limited to the current puzzle or to some recent
core software change)

**Comment by Raceous** [comment] 2020-05-25 02:09
The previous 3 grids have also stopped working. LP.html and NJC.html appear the same as above. WH.html (Wormholes) appears as a completely blank page.
Screenshots of console output follow. (Let me know if you would prefer these as text)

![image](https://user-images.githubusercontent.com/54013910/82771655-97f02b80-9df1-11ea-8de2-1aa4cfe47fbb.png)

![image](https://user-images.githubusercontent.com/54013910/82771693-b2c2a000-9df1-11ea-8616-3a773a311cd0.png)

![image](https://user-images.githubusercontent.com/54013910/82771723-ccfc7e00-9df1-11ea-84e7-bbc1a0484dc3.png)

![image](https://user-images.githubusercontent.com/54013910/82771815-1351dd00-9df2-11ea-8d3f-770dad574442.png)

**Comment by viresh-ratnakar** [comment] 2020-05-25 02:54
Looks like the error thrown at exolve-m.js:610 is the/a core problem. This
code was indeed added when I added non-English support recently.

try {
    languageScript = 'Devanagari'
    scriptRE = new RegExp('\\p{Script=' + languageScript + '}', 'u')
    scriptLowerCaseRE = new RegExp('\\p{Lowercase}', 'u')
} catch {
}

Can you please type these lines in the browser's JavaScript  console, one
at a time, and let me know what error messages pop up, when you get the
chance. I'm expecting some syntax errors. And then I want to check if the
syntax errors go away with some easy fixes.

**Comment by Raceous** [comment] 2020-05-25 03:05
Reopened In.html and copied the whole code fragment:
![image](https://user-images.githubusercontent.com/54013910/82774490-de498880-9df9-11ea-9bba-6c6646ace053.png)

**Comment by viresh-ratnakar** [comment] 2020-05-25 04:57
OK, thanks! Sorry, but we'll have to drill down a bit more. Here are variants aht ablate various aspects of the above. Please try them separately.

1.
try {
    languageScript = 'Devanagari'
  catch {
}

2.
    scriptLowerCaseRE = new RegExp('\\p{Lowercase}', 'u')

3.
scriptRE = new RegExp('test1', 'u')

4.
scriptRE = new RegExp('\\test2', 'u')

5.
try {
    scriptRE = new RegExp('test1', 'u')
catch {
}

6.
try {
    scriptRE = new RegExp('\\test1', 'u')
catch {
}

Or anything that useful variation can think of :-). Thanks!

**Comment by Raceous** [comment] 2020-05-25 17:59
Here you go:
![image](https://user-images.githubusercontent.com/54013910/82834711-bf3d0c00-9e76-11ea-9b69-3c38954fa1e5.png)

**Comment by viresh-ratnakar** [comment] 2020-05-25 20:59
Debugged through discussion, thanks!

Fixed with v0.73.

**Closed** 2020-05-26 21:27 UTC

**Comment by Raceous** [comment] 2020-05-26 21:38
Verified that the grid can now be viewed in Edge.
